name: Build

on: [push, pull_request]

jobs:
  build:
    uses: ernestojeda/edgex-global-pipelines/.github/workflows/build.yml@github-actions
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: nexus3.edgexfoundry.org:10004/device-usb-camera:latest
          # load: true
          platforms: linux/amd64,linux/arm64
      - name: Debug
        run: docker images